---
- name: test win playbook
  hosts: windows
  tasks:
  
  - name: Install git
    win_chocolatey:
      name: git
      state: present
      
  - name: Install Postgresql
    win_chocolatey:
      name: putty
      state: present
